/*
HW_04_C
Jeremy Stark
10/09/2018
A program which read in the two x,y-coordinate pairs,
and determine the equation of the line that connects
the two points. The program will output the equation
of the line in slope-intercept form.
*/
#include <stdio.h>

//Reads in a value, specifically for X
int readX()
{
	int x;

	printf("Please Input your x value: \n");
	scanf("%d", &x);

	return x;
}

//Reads in a value, specifically for Y
int readY()
{
	int y;

	printf("Please Input your y value: \n");
	scanf("%d", &y);

	return y;
}

//Calculates and returns (as a double) the slope of the line between the two (x,y) points.
double calcSlope(int x1, int x2, int y1, int y2)
{
	double slope = ((double)(y2-y1)/(double)(x2-x1));

	return slope;
}

//Calculates and returns (as a double) the Y-Intercept of
//the line generated by the line between two (x,y) points.
double calcYIntercept(double slope, int x1, int y1)
{
	double intercept = (double)(y1 - slope * x1);

	return intercept;
}

//Main Method
int main(void)
{
	//Variables
	int x1 = readX();
	int y1 = readY();
	int x2 = readX();
	int y2 = readY();
	double slope = calcSlope(x1, x2, y1, y2);
	double intercept = calcYIntercept(slope, x1, y1);

	//Print statements
	printf("Y = %0.2lfx + %0.2lf\n", slope, intercept);

	return 0;
}
